// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAv8pp7iQqQdPcHM3lHKtmx-wcz44GKc',
    appId: '1:271582396183:web:10e2552c851b6e59c2c152',
    messagingSenderId: '271582396183',
    projectId: 'touch-grass-gt',
    authDomain: 'touch-grass-gt.firebaseapp.com',
    storageBucket: 'touch-grass-gt.appspot.com',
    measurementId: 'G-SGBLD3VKQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbMbrDpT6T8LTXjJ4XlzcIDGPYS1qij8',
    appId: '1:271582396183:android:0f8db854c3d97da5c2c152',
    messagingSenderId: '271582396183',
    projectId: 'touch-grass-gt',
    storageBucket: 'touch-grass-gt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYKyi6C6RSRLJjYNd68mZM39Zrs_IYDmw',
    appId: '1:271582396183:ios:faba5decb1a31fabc2c152',
    messagingSenderId: '271582396183',
    projectId: 'touch-grass-gt',
    storageBucket: 'touch-grass-gt.appspot.com',
    iosBundleId: 'com.example.touchGrass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYKyi6C6RSRLJjYNd68mZM39Zrs_IYDmw',
    appId: '1:271582396183:ios:faba5decb1a31fabc2c152',
    messagingSenderId: '271582396183',
    projectId: 'touch-grass-gt',
    storageBucket: 'touch-grass-gt.appspot.com',
    iosBundleId: 'com.example.touchGrass',
  );
}
